### ISSUE TITLE
Cannot add a todo

### ISSUE THREAD

**Issue by ghost** [elgris/microservice-app-example#13]
"Error occured while trying to proxy to: 192.168.42.129:30008/todos". Response code: 504

This happens on MiniKube

![image](https://user-images.githubusercontent.com/5337267/35972216-904f4a56-0cd9-11e8-8724-5c4dc3b1c473.png)

**Comment by elgris** [comment]
Hi @eivantsov ! Thanks for your message, the problem is going to be fixed by #14

**Comment by ghost** [comment]
I added a redis deployment and it worked even without log processor.

**Comment by elgris** [comment]
@eivantsov that's true, it will work, but that's not the whole picture. And something needs to consume those messages from Redis.

**Comment by elgris** [comment]
considering solved
