### ISSUE TITLE
Add support for Kubernetes

### ISSUE THREAD

**Issue by ilyeshammadi** [elgris/microservice-app-example#2]
I'm working on a similar example project, and would like to suggest that we add also support for Kubernetes so that folks can see a working example using a real cluster in local for example with Minikube.

**Comment by bodyno** [comment]
I think developed only use docker compose is enough. And on test and production environment we use Kubernetes. That will be efficienty. Untile Docker support Kubernetes natively. It will be much easier more.

**Comment by elgris** [comment]
@Ilyes-Hammadi thanks for suggestion, that's actually the next step in a roadmap

**Comment by davidpkatz** [comment]
Feel free to check out our To Dos project, it uses an OpenAPI contract, has kubernetes deployments, end-to-end tests and uses React and NodeJS microservices: https://github.com/ClearPointNZ/connect-simple-todos-app

You're welcome to fork it or use any of the components. Thanks for this example app, it's always fun to learn from different implementations.

**Comment by ilyeshammadi** [comment]
I have created new a [pull request](https://github.com/elgris/microservice-app-example/pull/9) to solve this issue.

**Comment by elgris** [comment]
closed as corresponding PR is already there, thanks @Ilyes-Hammadi
